server:
  port: 8082

spring:
  application:
    name: etl-processing-service

# ETL Configuration
etl:
  batch:
    size: 100
  processing:
    interval: 300000  # 5 minutes in milliseconds

# AWS Configuration (for production)
aws:
  region: us-east-1
  glue:
    job-name: weather-etl-job
  s3:
    bucket: weather-data-lake

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.aws.etl: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
